"use client";

import { ChangeEvent, useMemo, useState } from "react";
import { Pagination, pageItems } from "../../components/Pagination";
import { normalizeRegistration } from "../../utils/registration";
import { logAudit } from "../../utils/localAudit";
import { deleteSharedDataRecords, saveSharedData, sharedKeys } from "../../services/firebase/sharedData";

type Vehicle = { id: string; registration: string; normalizedRegistration: string; vehicleType?: string; division?: string; originArea?: string; operatorCategory?: string; company?: string; concessionaire?: string; route?: string; active?: boolean };
type Driver = { id: string; fullName: string; telephone?: string; active?: boolean };
type ExistingEntry = { id: string; operationDate: string; registration: string; arrivalTime?: string; grossKg: number; tareKg: number; [key: string]: unknown };
type CellValue = string | number | boolean | Date | null | undefined | { result?: unknown; text?: string; richText?: { text: string }[] };
type SheetData = { name: string; rows: CellValue[][] };
type ImportedRow = {
  sourceRow: number; ticket: string; operationDate: string; registration: string; division: string; originArea: string; operatorCategory: string; company: string; routeSource: string;
  driverName: string; driverPhone: string; arrivalTime: string; departureTime: string; grossKg: number; tareKg: number; netKg: number;
};
type ReviewedRow = ImportedRow & { key: string; vehicle?: Vehicle; driver?: Driver; errors: string[]; warnings: string[]; duplicate: boolean };

const entriesKey = "buyala.local.entries.v1";
const vehiclesKey = "buyala.local.vehicles.v1";
const driversKey = "buyala.local.drivers.v1";
const aliases: Record<keyof ImportedRow, string[]> = {
  sourceRow: [], ticket: ["ticket", "ticket no", "ticket number", "local ticket"], operationDate: ["date", "operation date", "transaction date"],
  registration: ["registration", "registration no", "reg no", "reg. no.", "vehicle registration", "number plate"], division: ["division", "kampala division"],
  originArea: ["origin", "origin area"], operatorCategory: ["operator", "operator category", "concessionaire y/n", "concessionaire"], company: ["company", "company owner", "company / owner", "owner"],
  routeSource: ["collection route", "collection site / route", "collection site route", "route", "route source", "source"], driverName: ["driver", "driver name"],
  driverPhone: ["telephone", "phone", "phone number", "tel", "tel."], arrivalTime: ["arrival", "arrival time"], departureTime: ["departure", "departure time"],
  grossKg: ["gross", "gross kg", "gross weight", "gross wt", "gross wt kg", "gross weight kg"], tareKg: ["tare", "tare kg", "tare weight", "tare wt", "tare wt kg", "tare weight kg"], netKg: ["net", "net kg", "net weight", "net wt", "net wt kg", "net weight kg"],
};

function read<T>(key: string): T[] { try { const value = JSON.parse(localStorage.getItem(key) ?? "[]") as T[]; return Array.isArray(value) ? value : []; } catch { return []; } }
function cellText(value: CellValue): string {
  if (value == null) return ""; if (value instanceof Date) return value.toISOString();
  if (typeof value === "object") { if ("result" in value && value.result != null) return cellText(value.result as CellValue); if ("text" in value && value.text) return value.text; if ("richText" in value && value.richText) return value.richText.map((part) => part.text).join(""); }
  return String(value).trim();
}
function headerKey(value: CellValue) { return cellText(value).toLowerCase().replace(/[\n\r]+/g, " ").replace(/[().]/g, "").replace(/[/_-]+/g, " ").replace(/\s+/g, " ").trim(); }
const aliasLookup = new Map(Object.entries(aliases).flatMap(([field, names]) => names.map((name) => [headerKey(name), field] as const)));
function findHeader(rows: CellValue[][]) {
  let best = { index: -1, score: 0, columns: new Map<string, number>() };
  rows.slice(0, 25).forEach((row, index) => { const columns = new Map<string, number>(); row.forEach((value, column) => { const field = aliasLookup.get(headerKey(value)); if (field && !columns.has(field)) columns.set(field, column); }); if (columns.size > best.score) best = { index, score: columns.size, columns }; });
  return best.score >= 4 ? best : null;
}
function excelDate(value: CellValue) {
  if (value instanceof Date && !Number.isNaN(value.getTime())) return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`;
  if (typeof value === "number" && value > 20000 && value < 80000) return new Date(Date.UTC(1899, 11, 30) + Math.round(value) * 86400000).toISOString().slice(0, 10);
  const text = cellText(value).trim(); if (!text) return "";
  const iso = text.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/); if (iso) return `${iso[1]}-${iso[2].padStart(2, "0")}-${iso[3].padStart(2, "0")}`;
  const local = text.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{2,4})/); if (local) { const year = local[3].length === 2 ? `20${local[3]}` : local[3]; return `${year}-${local[2].padStart(2, "0")}-${local[1].padStart(2, "0")}`; }
  const parsed = new Date(text); return Number.isNaN(parsed.getTime()) ? "" : `${parsed.getFullYear()}-${String(parsed.getMonth() + 1).padStart(2, "0")}-${String(parsed.getDate()).padStart(2, "0")}`;
}
function excelTime(value: CellValue) {
  if (value instanceof Date) return `${String(value.getHours()).padStart(2, "0")}:${String(value.getMinutes()).padStart(2, "0")}`;
  if (typeof value === "number" && value >= 0 && value < 1) { const minutes = Math.round(value * 1440) % 1440; return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`; }
  const text = cellText(value).trim(); if (!text) return ""; const match = text.match(/(\d{1,2}):(\d{2})\s*(am|pm)?/i); if (!match) return text;
  let hour = Number(match[1]); if (match[3]?.toLowerCase() === "pm" && hour < 12) hour += 12; if (match[3]?.toLowerCase() === "am" && hour === 12) hour = 0; return `${String(hour).padStart(2, "0")}:${match[2]}`;
}
function numeric(value: CellValue) { const cleaned = cellText(value).replace(/,/g, "").replace(/\s*(kg|kgs)$/i, ""); const number = Number(cleaned); return Number.isFinite(number) ? number : 0; }
function valueAt(row: CellValue[], columns: Map<string, number>, field: keyof ImportedRow) { const column = columns.get(field); return column == null ? undefined : row[column]; }
function parseSheet(sheet: SheetData): ImportedRow[] {
  const header = findHeader(sheet.rows); if (!header) return [];
  return sheet.rows.slice(header.index + 1).map((row, offset) => ({
    sourceRow: header.index + offset + 2, ticket: cellText(valueAt(row, header.columns, "ticket")), operationDate: excelDate(valueAt(row, header.columns, "operationDate")), registration: cellText(valueAt(row, header.columns, "registration")).toUpperCase(),
    division: cellText(valueAt(row, header.columns, "division")), originArea: cellText(valueAt(row, header.columns, "originArea")), operatorCategory: cellText(valueAt(row, header.columns, "operatorCategory")), company: cellText(valueAt(row, header.columns, "company")), routeSource: cellText(valueAt(row, header.columns, "routeSource")),
    driverName: cellText(valueAt(row, header.columns, "driverName")), driverPhone: cellText(valueAt(row, header.columns, "driverPhone")), arrivalTime: excelTime(valueAt(row, header.columns, "arrivalTime")), departureTime: excelTime(valueAt(row, header.columns, "departureTime")),
    grossKg: numeric(valueAt(row, header.columns, "grossKg")), tareKg: numeric(valueAt(row, header.columns, "tareKg")), netKg: numeric(valueAt(row, header.columns, "netKg")),
  })).filter((row) => row.registration || row.grossKg || row.tareKg || row.netKg);
}
function normalizedName(value: string) { return value.trim().toLowerCase().replace(/\s+/g, " "); }
function duplicateKey(row: Pick<ImportedRow, "operationDate" | "registration" | "arrivalTime" | "grossKg" | "tareKg">) { return [row.operationDate, normalizeRegistration(row.registration), row.arrivalTime, row.grossKg, row.tareKg].join("|"); }
function completedAt(row: ImportedRow) { const time = row.departureTime || row.arrivalTime || "12:00"; const date = new Date(`${row.operationDate}T${time}:00+03:00`); return Number.isNaN(date.getTime()) ? new Date().toISOString() : date.toISOString(); }
function category(value: string) { const normalized = value.trim().toLowerCase(); if (["y", "yes", "concessionaire"].includes(normalized)) return "Concessionaire"; if (["n", "no", "non concessionaire", "non-concessionaire"].includes(normalized)) return "Non-concessionaire"; return value.trim(); }

export function HistoricalImportView({ actorName, role }: { actorName: string; role: "Engineer" | "System Admin" }) {
  const [fileName, setFileName] = useState(""); const [sheets, setSheets] = useState<SheetData[]>([]); const [sheetName, setSheetName] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [selected, setSelected] = useState<Set<string>>(new Set()); const [filter, setFilter] = useState("all"); const [page, setPage] = useState(1);
  const [replaceDate, setReplaceDate] = useState(""); const [replacePhrase, setReplacePhrase] = useState(""); const [replacing, setReplacing] = useState(false);
  const sourceRows = useMemo(() => parseSheet(sheets.find((sheet) => sheet.name === sheetName) ?? { name: "", rows: [] }), [sheets, sheetName]);
  const reviewed = useMemo<ReviewedRow[]>(() => {
    const vehicles = read<Vehicle>(vehiclesKey); const drivers = read<Driver>(driversKey); const existing = read<ExistingEntry>(entriesKey); const existingKeys = new Set(existing.map(duplicateKey)); const fileKeys = new Set<string>();
    return sourceRows.map((row) => { const normalized = normalizeRegistration(row.registration); const vehicle = vehicles.find((item) => item.active !== false && item.normalizedRegistration === normalized); const driver = drivers.find((item) => item.active !== false && normalizedName(item.fullName) === normalizedName(row.driverName)); const errors: string[] = []; const warnings: string[] = [];
      if (!row.operationDate) errors.push("Missing or invalid date"); if (!normalized) errors.push("Missing registration"); if (row.grossKg <= 0) errors.push("Gross weight is missing"); if (row.tareKg <= 0) errors.push("Tare weight is missing"); if (row.tareKg > row.grossKg && row.grossKg > 0) errors.push("Tare is greater than gross"); const calculated = row.grossKg - row.tareKg; if (calculated <= 0 && row.grossKg > 0 && row.tareKg > 0) errors.push("Net weight is not positive"); if (row.netKg > 0 && Math.abs(row.netKg - calculated) > 1) errors.push("Net does not equal gross minus tare");
      if (!vehicle) warnings.push("Vehicle unmatched"); if (!row.driverName) warnings.push("Driver name missing"); else if (!driver) warnings.push("Driver unmatched"); if (!row.routeSource && !vehicle?.route) warnings.push("Route missing"); if (!row.departureTime) warnings.push("Departure time missing"); if (!row.division && !vehicle?.division) warnings.push("Division unconfirmed");
      const key = duplicateKey(row); const duplicate = existingKeys.has(key) || fileKeys.has(key); fileKeys.add(key); if (duplicate) errors.push("Possible duplicate"); return { ...row, key: `${key}|${row.sourceRow}`, vehicle, driver, errors, warnings, duplicate };
    });
  }, [sourceRows]);
  const visible = reviewed.filter((row) => filter === "ready" ? !row.errors.length : filter === "attention" ? row.errors.length > 0 : true); const paged = pageItems(visible, page, 15); const ready = reviewed.filter((row) => !row.errors.length); const selectedReady = ready.filter((row) => selected.has(row.key));
  const rowsForReplacement = reviewed.filter((row) => row.operationDate === replaceDate); const invalidReplacementRows = rowsForReplacement.filter((row) => row.errors.some((error) => error !== "Possible duplicate")); const repeatedReplacementRows = new Set(rowsForReplacement.map(duplicateKey)).size !== rowsForReplacement.length; const existingOnReplaceDate = replaceDate ? read<ExistingEntry>(entriesKey).filter((entry) => entry.operationDate === replaceDate) : [];

  async function openFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return; setLoading(true); setMessage(""); setSelected(new Set());
    try { if (!file.name.toLowerCase().endsWith(".xlsx")) throw new Error("Please use an .xlsx Excel workbook. In Excel, use Save As if the old file is .xls."); const ExcelJS = await import("exceljs"); const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(await file.arrayBuffer()); const next = workbook.worksheets.map((worksheet) => ({ name: worksheet.name, rows: Array.from({ length: worksheet.rowCount }, (_, index) => { const values = worksheet.getRow(index + 1).values as CellValue[]; return values.slice(1); }) })); const usable = next.filter((sheet) => findHeader(sheet.rows)); if (!usable.length) throw new Error("No transaction table was found. Check that the workbook has headers such as Date, Registration, Gross and Tare."); setFileName(file.name); setSheets(usable); setSheetName(usable[0].name); setPage(1); setMessage(`${usable.length} transaction sheet${usable.length === 1 ? "" : "s"} found. Review the rows before importing.`);
    } catch (error) { setFileName(""); setSheets([]); setSheetName(""); setMessage(error instanceof Error ? error.message : "The workbook could not be read."); } finally { setLoading(false); event.target.value = ""; }
  }
  function selectReady() { setSelected(new Set(ready.map((row) => row.key))); }
  function makeAdditions(rows: ReviewedRow[], batchId: string, now: string) { return rows.map((row, index) => { const vehicle = row.vehicle; const driver = row.driver; const calculatedNet = row.grossKg - row.tareKg; const operator = category(row.operatorCategory) || vehicle?.operatorCategory || (vehicle?.concessionaire === "Yes" ? "Concessionaire" : vehicle?.concessionaire === "No" ? "Non-concessionaire" : undefined); return {
    id: crypto.randomUUID(), facilityId: "buyala", localTicket: row.ticket || `HIST-${row.operationDate.replaceAll("-", "")}-${String(index + 1).padStart(3, "0")}`, createdBy: actorName, createdAt: now, transactionAt: completedAt(row), updatedBy: actorName, updatedAt: now,
    registration: row.registration.trim().toUpperCase(), vehicleId: vehicle?.id, vehicleMatched: Boolean(vehicle), vehicleType: vehicle?.vehicleType, division: row.division || vehicle?.division, originArea: row.originArea || vehicle?.originArea, operatorCategory: operator, company: row.company || vehicle?.company, concessionaire: operator === "Concessionaire" ? "Yes" : operator === "Non-concessionaire" ? "No" : vehicle?.concessionaire,
    driverName: row.driverName || "Not recorded", driverId: driver?.id, driverMatched: Boolean(driver), driverPhone: row.driverPhone || driver?.telephone || "", routeSource: row.routeSource || vehicle?.route || "Historical import — route not recorded", arrivalTime: row.arrivalTime || "00:00", departureTime: row.departureTime || undefined,
    grossKg: row.grossKg, tareKg: row.tareKg, netKg: calculatedNet, tareCaptureMode: "UNCONFIRMED", status: "COMPLETED", operationDate: row.operationDate, completedAt: completedAt(row), importBatchId: batchId, importSourceFile: fileName, importedAt: now, importedBy: actorName, importSourceSheet: sheetName, importSourceRow: row.sourceRow,
  }; }); }
  function importRows() {
    if (!selectedReady.length) return setMessage("Select at least one ready row first."); const now = new Date().toISOString(); const batchId = crypto.randomUUID(); const existing = read<ExistingEntry>(entriesKey); const additions = makeAdditions(selectedReady, batchId, now); saveSharedData(sharedKeys.entries, [...existing, ...additions]); logAudit(actorName, role, "HISTORICAL_TRANSACTIONS_IMPORTED", `Imported ${additions.length} completed transactions from ${fileName} / ${sheetName}. Original dates preserved.`, batchId); setSelected(new Set()); setMessage(`${additions.length} historical transaction${additions.length === 1 ? "" : "s"} saved. They are queued for Firebase synchronization and will appear in reports under their original dates.`);
  }
  function downloadReplacementBackup(records: ExistingEntry[]) { const blob = new Blob([JSON.stringify({ application: "Buyala Waste Operations", backupType: "before-date-replacement", date: replaceDate, exportedAt: new Date().toISOString(), transactions: records }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `buyala-before-replace-${replaceDate}.json`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 2000); }
  async function replaceTransactionsForDate() {
    const confirmation = `REPLACE ${replaceDate}`; if (role !== "System Admin") return; if (!navigator.onLine) return setMessage("Connect to the internet before replacing a date. This safety action must update Firebase immediately."); if (!replaceDate || !rowsForReplacement.length) return setMessage("Choose a date that has replacement rows in the uploaded Excel sheet."); if (invalidReplacementRows.length || repeatedReplacementRows) return setMessage("The replacement rows contain invalid weights, dates, or repeated transactions. Correct the Excel file before replacing this date."); if (replacePhrase !== confirmation) return setMessage(`Type ${confirmation} exactly to continue.`);
    setReplacing(true); setMessage(""); const existing = read<ExistingEntry>(entriesKey); const removed = existing.filter((entry) => entry.operationDate === replaceDate); const retained = existing.filter((entry) => entry.operationDate !== replaceDate); downloadReplacementBackup(removed);
    try { await deleteSharedDataRecords(sharedKeys.entries, removed.map((entry) => entry.id)); const now = new Date().toISOString(); const batchId = crypto.randomUUID(); const additions = makeAdditions(rowsForReplacement, batchId, now); saveSharedData(sharedKeys.entries, [...retained, ...additions]); logAudit(actorName, role, "TRANSACTION_DATE_REPLACED", `Replaced ${removed.length} existing transactions dated ${replaceDate} with ${additions.length} transactions from ${fileName} / ${sheetName}. A pre-replacement backup was downloaded.`, batchId); setReplacePhrase(""); setSelected(new Set()); setMessage(`${replaceDate} replaced successfully: ${removed.length} old transaction${removed.length === 1 ? "" : "s"} removed and ${additions.length} Excel transaction${additions.length === 1 ? "" : "s"} added. Firebase synchronization is in progress.`); }
    catch { setMessage("The date could not be replaced completely. Keep the downloaded backup and try again while connected as System Admin."); } finally { setReplacing(false); }
  }

  return <div className="historical-import-page"><div className="historical-heading"><div><p className="master-kicker">ENGINEER DATA TOOL</p><h2>Historical Excel import</h2><p>Bring earlier weighbridge transactions into Buyala without changing their original dates.</p></div><span>{role} only</span></div>
    <section className="import-steps"><article><b>1</b><div><strong>Choose Excel file</strong><p>Use the original workbook or a Buyala Excel export.</p></div></article><article><b>2</b><div><strong>Preview and match</strong><p>Check dates, weights, duplicates, vehicles and drivers.</p></div></article><article><b>3</b><div><strong>Approve and synchronize</strong><p>Only selected ready rows are added to Firebase.</p></div></article></section>
    <section className="import-upload"><label className="import-file-button">{loading ? "Reading workbook…" : "Choose .xlsx file"}<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={openFile} disabled={loading} /></label><div><strong>{fileName || "No workbook selected"}</strong><p>Your file is read locally. Nothing is saved until you approve rows below.</p></div></section>
    {sheets.length > 0 && <><section className="import-controls"><label>Transaction sheet<select value={sheetName} onChange={(event) => { setSheetName(event.target.value); setSelected(new Set()); setPage(1); }}><>{sheets.map((sheet) => <option key={sheet.name}>{sheet.name}</option>)}</></select></label><div className="import-counts"><span><b>{reviewed.length}</b> rows</span><span className="ready"><b>{ready.length}</b> ready</span><span className="attention"><b>{reviewed.length - ready.length}</b> need attention</span></div></section>
      <section className="import-preview"><div className="import-toolbar"><div><button className={filter === "all" ? "active" : ""} onClick={() => { setFilter("all"); setPage(1); }}>All</button><button className={filter === "ready" ? "active" : ""} onClick={() => { setFilter("ready"); setPage(1); }}>Ready</button><button className={filter === "attention" ? "active" : ""} onClick={() => { setFilter("attention"); setPage(1); }}>Needs attention</button></div><button onClick={selectReady}>Select all ready rows</button></div>
        <div className="import-table-wrap"><table><thead><tr><th>Select</th><th>Excel row</th><th>Date</th><th>Registration</th><th>Driver / route</th><th>Gross</th><th>Tare</th><th>Net</th><th>Review</th></tr></thead><tbody>{paged.items.map((row) => <tr key={row.key} className={row.errors.length ? "invalid" : "valid"}><td><input type="checkbox" aria-label={`Select Excel row ${row.sourceRow}`} checked={selected.has(row.key)} disabled={row.errors.length > 0} onChange={(event) => setSelected((current) => { const next = new Set(current); if (event.target.checked) next.add(row.key); else next.delete(row.key); return next; })} /></td><td>{row.sourceRow}</td><td>{row.operationDate || "—"}</td><td><strong>{row.registration || "—"}</strong><small>{row.vehicle ? "Vehicle matched ✓" : "Vehicle unmatched"}</small></td><td>{row.driverName || "Not recorded"}<small>{row.routeSource || row.vehicle?.route || "Route not recorded"}</small></td><td>{row.grossKg ? row.grossKg.toLocaleString() : "—"}</td><td>{row.tareKg ? row.tareKg.toLocaleString() : "—"}</td><td>{row.grossKg > row.tareKg ? (row.grossKg - row.tareKg).toLocaleString() : "—"}</td><td><span className={row.errors.length ? "row-error" : row.warnings.length ? "row-warning" : "row-ready"}>{row.errors.length ? row.errors.join("; ") : row.warnings.length ? row.warnings.join("; ") : "Ready ✓"}</span></td></tr>)}</tbody></table></div><Pagination page={paged.currentPage} totalItems={visible.length} pageSize={15} onChange={setPage} label="import rows" />
        <div className="import-approval"><div><strong>{selectedReady.length} row{selectedReady.length === 1 ? "" : "s"} selected</strong><p>Imported rows become completed transactions. Their Excel dates control dashboards and reports.</p></div><button disabled={!selectedReady.length} onClick={importRows}>Import selected rows</button></div>
      </section></>}
    {role === "System Admin" && sheets.length > 0 && <section className="replace-date-panel"><div className="replace-date-heading"><div><p className="master-kicker">SYSTEM ADMIN SAFETY TOOL</p><h3>Replace all transactions for one date</h3><p>Use this when the uploaded Excel sheet is the complete and authoritative record for a day.</p></div><span>Backup required</span></div><div className="replace-date-warning"><strong>This removes every existing transaction on the selected date from this device and Firebase.</strong><p>Other dates, vehicles, drivers, materials recovery and accounts are not affected.</p></div><div className="replace-date-grid"><label>Date to replace<input type="date" value={replaceDate} onChange={(event) => { setReplaceDate(event.target.value); setReplacePhrase(""); }} /></label><article><span>Currently in system</span><strong>{existingOnReplaceDate.length}</strong><small>transactions dated {replaceDate || "—"}</small></article><article><span>Replacement from Excel</span><strong>{rowsForReplacement.length}</strong><small>{invalidReplacementRows.length || repeatedReplacementRows ? "Excel rows need correction" : "valid rows for this date"}</small></article></div>{replaceDate && <label className="replace-confirm">Type <b>REPLACE {replaceDate}</b> to confirm<input value={replacePhrase} onChange={(event) => setReplacePhrase(event.target.value)} placeholder={`REPLACE ${replaceDate}`} autoComplete="off" /></label>}<button className="replace-date-button" disabled={replacing || !replaceDate || !rowsForReplacement.length || Boolean(invalidReplacementRows.length) || repeatedReplacementRows || replacePhrase !== `REPLACE ${replaceDate}`} onClick={replaceTransactionsForDate}>{replacing ? "Backing up and replacing…" : `Back up and replace ${replaceDate || "selected date"}`}</button></section>}
    {message && <p className="import-message" role="status">{message}</p>}<section className="import-safety"><strong>Safety rules</strong><ul><li>Rows with invalid dates, weights, or duplicates cannot be selected.</li><li>Unmatched vehicles and drivers are allowed but clearly flagged for later correction.</li><li>The source file, sheet, row number, importer and batch are retained for audit.</li><li>Keep the original Excel workbook as your independent backup.</li></ul></section>
  </div>;
}
