"use client";

import { useState } from "react";
import { prepareResetBackup, resetTrainingData, type ResetScope } from "../../services/firebase/adminReset";

function downloadBackup(data: Record<string, unknown>, scope: ResetScope) { const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `buyala-before-${scope}-reset-${new Date().toISOString().replaceAll(":", "-").slice(0, 19)}.json`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 2000); }

export function TrainingResetPanel({ adminName }: { adminName: string }) {
  const [scope, setScope] = useState<ResetScope>("transactions"); const [backupReady, setBackupReady] = useState(false); const [phrase, setPhrase] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const confirmation = scope === "transactions" ? "CLEAR TRANSACTIONS" : scope === "operations" ? "CLEAR TRAINING DATA" : "START BUYALA FRESH";
  function choose(next: ResetScope) { setScope(next); setBackupReady(false); setPhrase(""); setPassword(""); setMessage(""); }
  async function prepare() { setBusy(true); setMessage("Preparing a recoverable Firebase backup…"); try { const backup = await prepareResetBackup(scope); downloadBackup(backup, scope); setBackupReady(true); setMessage("Backup downloaded. Confirm that the file is saved before completing the reset."); } catch { setMessage("The backup could not be prepared. Nothing was deleted. Check the internet connection."); } finally { setBusy(false); } }
  async function execute() { if (!backupReady || phrase !== confirmation || !password) return; setBusy(true); setMessage("Clearing the selected records safely…"); try { await resetTrainingData(scope, password, adminName); setMessage("Reset complete. Preserved data remains available. Reloading the clean workspace…"); window.setTimeout(() => window.location.reload(), 1200); } catch { setMessage("Reset stopped. The System Admin password may be incorrect or Firebase could not complete the operation. Existing records remain protected by the downloaded backup."); setBusy(false); } }
  const resetLabel = scope === "transactions" ? "Back up and clear transactions" : scope === "operations" ? "Back up and clear training activity" : "Back up and start fresh";
  return <section className="training-reset-panel"><div className="training-reset-heading"><div><p className="master-kicker">SYSTEM ADMIN SAFETY TOOL</p><h3>Data reset</h3><p>Create a recoverable backup, then remove only the selected shared data.</p></div><span>Accounts always preserved</span></div><div className="reset-scope-grid"><button className={scope === "transactions" ? "selected" : ""} onClick={() => choose("transactions")}><b>Clear transactions only</b><span>Removes all weighbridge transaction records. Keeps vehicles, drivers, recovered-material entries, audit history, accounts and settings.</span><small>Selected for a clean operational start</small></button><button className={scope === "operations" ? "selected" : ""} onClick={() => choose("operations")}><b>Clear all training activity</b><span>Removes transactions, recovered-material entries, operational audit history and diagnostics. Keeps vehicles, drivers and staff accounts.</span><small>Use only when all training activity should go</small></button><button className={scope === "fresh" ? "selected" : ""} onClick={() => choose("fresh")}><b>Start operational data fresh</b><span>Also removes the vehicle and driver master lists. Staff accounts, roles and app installation remain.</span><small>Use only if master data should also be removed</small></button></div><div className="reset-guard"><strong>This action removes shared Firebase records from every connected device.</strong><p>Offline devices receive a reset marker and discard the cleared data before they can synchronize again.</p></div><div className="reset-steps"><button className="backup-first" onClick={prepare} disabled={busy}>{busy && !backupReady ? "Preparing backup…" : backupReady ? "Download backup again" : "1. Download required backup"}</button>{backupReady && <><label>2. Type <b>{confirmation}</b><input value={phrase} onChange={(event) => setPhrase(event.target.value)} placeholder={confirmation} autoComplete="off" /></label><label>3. Current System Admin password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" /></label><button className="danger-reset" onClick={execute} disabled={busy || phrase !== confirmation || !password}>{busy ? "Resetting safely…" : resetLabel}</button></>}</div>{message && <p className="reset-message" role="status">{message}</p>}</section>;
}
