"use client";

import { useEffect, useMemo, useState } from "react";
import { normalizeRegistration } from "../../utils/registration";
import { logAudit } from "../../utils/localAudit";

type VehicleRecord = { id: string; registration: string; normalizedRegistration: string; vehicleType: string; company: string; concessionaire: string; operatorCategory?: string; originArea?: string; division: string; route: string; tareKg?: number; active?: boolean };
type DriverRecord = { id: string; fullName: string; telephone: string; notes: string; active?: boolean };
type Entry = { id: string; facilityId: "buyala"; localTicket: string; createdBy?: string; createdAt?: string; updatedBy?: string; updatedAt?: string; registration: string; vehicleId?: string; vehicleMatched: boolean; vehicleType?: string; division?: string; originArea?: string; operatorCategory?: string; company?: string; concessionaire?: string; driverName: string; driverId?: string; driverMatched: boolean; driverPhone: string; routeSource: string; arrivalTime: string; departureTime?: string; grossKg: number; tareKg: number; netKg: number; tareCaptureMode: "UNCONFIRMED"; status: "OPEN" | "COMPLETED"; operationDate: string; completedAt: string };

const vehiclesKey = "buyala.local.vehicles.v1";
const driversKey = "buyala.local.drivers.v1";
const entriesKey = "buyala.local.entries.v1";
const resumeKey = "buyala.local.resumeEntryId";
const draftKey = "buyala.local.operationDraft.v1";
type OperationDraft = { step: number; registration: string; driverName: string; route: string; arrivalTime: string; gross: string; tare: string; departureTime: string; savedAt: string };

function readLocal<T>(key: string): T[] { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem(key) ?? "[]") as T[]; } catch { return []; } }
function readResumeEntry() { if (typeof window === "undefined") return null; const id = localStorage.getItem(resumeKey); return readLocal<Entry>(entriesKey).find((entry) => entry.id === id && entry.status === "OPEN") ?? null; }
function readDraft() { if (typeof window === "undefined") return null; try { return JSON.parse(localStorage.getItem(draftKey) ?? "null") as OperationDraft | null; } catch { return null; } }
function currentTime() { return new Date().toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", hour12: false }); }
function nextLocalTicket(entries: Entry[], date: string) { const sequence = entries.filter((entry) => entry.operationDate === date).length + 1; return `BUY-${date.replaceAll("-", "")}-${String(sequence).padStart(3, "0")}`; }

export function OperationsFlow({ onAddVehicle, onAddDriver, operatorName }: { onAddVehicle?: (registration: string) => void; onAddDriver?: (name: string) => void; operatorName?: string }) {
  const [resumeEntry] = useState<Entry | null>(readResumeEntry);
  const [restoredDraft, setRestoredDraft] = useState<OperationDraft | null>(() => resumeEntry ? null : readDraft());
  const [step, setStep] = useState(resumeEntry ? 4 : restoredDraft?.step ?? 1);
  const [vehicles] = useState<VehicleRecord[]>(() => readLocal<VehicleRecord>(vehiclesKey));
  const [drivers] = useState<DriverRecord[]>(() => readLocal<DriverRecord>(driversKey));
  const [registration, setRegistration] = useState(resumeEntry?.registration ?? restoredDraft?.registration ?? "");
  const [driverName, setDriverName] = useState(resumeEntry?.driverName ?? restoredDraft?.driverName ?? "");
  const [route, setRoute] = useState(resumeEntry?.routeSource ?? restoredDraft?.route ?? "");
  const [arrivalTime, setArrivalTime] = useState(() => resumeEntry?.arrivalTime ?? restoredDraft?.arrivalTime ?? currentTime());
  const [gross, setGross] = useState(resumeEntry ? String(resumeEntry.grossKg) : restoredDraft?.gross ?? "");
  const [tare, setTare] = useState(resumeEntry?.tareKg ? String(resumeEntry.tareKg) : restoredDraft?.tare ?? "");
  const [departureTime, setDepartureTime] = useState(() => restoredDraft?.departureTime ?? currentTime());
  const [error, setError] = useState("");
  const [completed, setCompleted] = useState<Entry | null>(null);
  const [confirmingCompletion, setConfirmingCompletion] = useState(false);

  const normalized = normalizeRegistration(registration);
  const vehicle = useMemo(() => vehicles.find((item) => item.active !== false && item.normalizedRegistration === normalized), [vehicles, normalized]);
  const driver = useMemo(() => drivers.find((item) => item.active !== false && item.fullName.trim().toLowerCase() === driverName.trim().toLowerCase()), [drivers, driverName]);
  const grossKg = Number(gross) || 0;
  const tareKg = Number(tare) || 0;
  const netKg = grossKg > 0 && tareKg > 0 && grossKg >= tareKg ? grossKg - tareKg : 0;
  const weightWarning = gross && (!Number.isFinite(Number(gross)) || grossKg <= 0) ? "Gross weight must be a positive number." : tare && (!Number.isFinite(Number(tare)) || tareKg <= 0) ? "Tare weight must be a positive number." : grossKg > 0 && tareKg > grossKg ? "Tare cannot be greater than gross." : grossKg > 0 && tareKg === grossKg ? "Gross and tare are equal, so net waste would be zero." : "";

  useEffect(() => {
    if (resumeEntry || completed) return;
    if (!registration.trim() && step === 1) { localStorage.removeItem(draftKey); return; }
    const draft: OperationDraft = { step: Math.min(step, 4), registration, driverName, route, arrivalTime, gross, tare, departureTime, savedAt: new Date().toISOString() };
    localStorage.setItem(draftKey, JSON.stringify(draft));
  }, [step, registration, driverName, route, arrivalTime, gross, tare, departureTime, resumeEntry, completed]);

  function nextFromVehicle() { setError(""); if (!normalized) return setError("Enter a registration number to continue."); if (vehicle) { setRoute(vehicle.route ?? ""); if (vehicle.tareKg) setTare(String(vehicle.tareKg)); } setRegistration(registration.trim().toUpperCase()); setStep(2); }
  function nextFromDriver() { setError(""); if (!driverName.trim()) return setError("Select a driver or enter the driver's name manually."); setStep(3); }
  function nextFromArrival() { setError(""); if (!route.trim()) return setError("Enter or select the collection route for this trip."); if (!arrivalTime) return setError("Enter the arrival time."); setStep(4); }
  function validateWeights(status: "OPEN" | "COMPLETED") { if (!Number.isFinite(Number(gross)) || grossKg <= 0) return "Gross weight must be greater than zero."; if (status === "COMPLETED" && (!Number.isFinite(Number(tare)) || tareKg <= 0)) return "Tare weight must be greater than zero."; if (tareKg > grossKg) return "Tare weight cannot be greater than gross weight. Please check both readings."; if (status === "COMPLETED" && netKg <= 0) return "Net waste must be greater than zero. Please check the gross and tare readings."; if (status === "COMPLETED" && !departureTime) return "Enter the departure time before completing the transaction."; return ""; }
  function reviewCompletion() { setError(""); const validation = validateWeights("COMPLETED"); if (validation) return setError(validation); setConfirmingCompletion(true); }
  function saveEntry(status: "OPEN" | "COMPLETED") {
    setError("");
    const validation = validateWeights(status);
    if (validation) return setError(validation);
    setConfirmingCompletion(false);
    const now = new Date().toISOString();
    const saved = readLocal<Entry>(entriesKey); const operationDate = resumeEntry?.operationDate ?? now.slice(0, 10);
    const entry: Entry = { id: resumeEntry?.id ?? crypto.randomUUID(), facilityId: "buyala", localTicket: resumeEntry?.localTicket ?? nextLocalTicket(saved, operationDate), createdBy: resumeEntry?.createdBy ?? operatorName, createdAt: resumeEntry?.createdAt ?? resumeEntry?.completedAt ?? now, updatedBy: operatorName, updatedAt: now, registration: registration.trim().toUpperCase(), vehicleId: vehicle?.id ?? resumeEntry?.vehicleId, vehicleMatched: resumeEntry?.vehicleMatched ?? Boolean(vehicle), vehicleType: vehicle?.vehicleType ?? resumeEntry?.vehicleType, division: vehicle?.division ?? resumeEntry?.division, originArea: vehicle?.originArea ?? resumeEntry?.originArea, operatorCategory: vehicle?.operatorCategory ?? (vehicle?.concessionaire === "Yes" ? "Concessionaire" : vehicle?.concessionaire === "No" ? "Non-concessionaire" : undefined) ?? resumeEntry?.operatorCategory, company: vehicle?.company ?? resumeEntry?.company, concessionaire: vehicle?.concessionaire ?? resumeEntry?.concessionaire, driverName: driverName.trim(), driverId: driver?.id ?? resumeEntry?.driverId, driverMatched: resumeEntry?.driverMatched ?? Boolean(driver), driverPhone: driver?.telephone ?? resumeEntry?.driverPhone ?? "", routeSource: route.trim(), arrivalTime, departureTime: status === "COMPLETED" ? departureTime : undefined, grossKg, tareKg: status === "OPEN" ? 0 : tareKg, netKg: status === "OPEN" ? 0 : netKg, tareCaptureMode: "UNCONFIRMED", status, operationDate, completedAt: now };
    const updated = resumeEntry ? saved.map((item) => item.id === entry.id ? entry : item) : [...saved, entry]; localStorage.setItem(entriesKey, JSON.stringify(updated)); logAudit(operatorName || "Unknown local user", "Operator", status === "OPEN" ? "TRANSACTION_OPENED" : resumeEntry ? "TRANSACTION_COMPLETED" : "TRANSACTION_RECORDED", status === "OPEN" ? `Saved ${entry.registration} with tare pending` : `Completed ${entry.registration} at ${entry.netKg.toLocaleString()} kg net`, entry.localTicket); localStorage.removeItem(resumeKey); localStorage.removeItem(draftKey); setCompleted(entry); setStep(5);
  }
  function reset() { localStorage.removeItem(resumeKey); localStorage.removeItem(draftKey); setRestoredDraft(null); setStep(1); setRegistration(""); setDriverName(""); setRoute(""); setArrivalTime(currentTime()); setGross(""); setTare(""); setDepartureTime(currentTime()); setError(""); setCompleted(null); setConfirmingCompletion(false); }

  const stepLabels = ["Vehicle", "Driver", "Source & arrival", "Weight", "Complete"];
  return <div className="operations-page">
    <div className="operations-heading"><div><p className="master-kicker">DAILY OPERATIONS</p><h2>Record vehicle</h2><p>Capture one weighbridge transaction at a time.</p></div><div className="local-status"><span /> Saved on this device</div></div>
    <ol className="stepper" aria-label="Transaction progress">{stepLabels.map((label, index) => <li key={label} className={step > index + 1 ? "done" : step === index + 1 ? "current" : ""}><span>{step > index + 1 ? "✓" : index + 1}</span><small>{label}</small></li>)}</ol>
    {restoredDraft && !resumeEntry && step < 5 && <div className="draft-restored"><strong>Draft restored</strong><span>Your unfinished vehicle entry was recovered from this device.</span><button onClick={reset}>Discard draft</button></div>}
    {step === 1 && normalized && !vehicle && <div className="quick-add-prompt"><div><strong>Keep this vehicle for future visits?</strong><span>Your current entry is saved as a draft.</span></div><button onClick={() => onAddVehicle?.(registration.trim().toUpperCase())}>＋ Add to Vehicles</button></div>}
    {step === 2 && driverName.trim() && !driver && <div className="quick-add-prompt"><div><strong>Keep this driver for future visits?</strong><span>Your current entry is saved as a draft.</span></div><button onClick={() => onAddDriver?.(driverName.trim())}>＋ Add to Drivers</button></div>}
    <section className="operation-card">
      {step === 1 && <div className="operation-step"><p className="step-label">STEP 1 OF 4</p><h3>Which vehicle has arrived?</h3><p className="step-help">Enter the registration number. Spaces and punctuation do not affect matching.</p><label className="large-input">Registration number<input value={registration} onChange={(event) => setRegistration(event.target.value)} placeholder="e.g. UBM 845Z" autoCapitalize="characters" /></label>{normalized && (vehicle ? <div className="match-card success"><span aria-hidden="true">✓</span><div><strong>{vehicle.registration}</strong><p>{[vehicle.vehicleType, vehicle.division, vehicle.company].filter(Boolean).join(" · ")}</p><small>Vehicle found in database</small></div></div> : <div className="match-card warning"><span aria-hidden="true">!</span><div><strong>Vehicle not registered</strong><p>{registration.trim().toUpperCase()} is not currently in the vehicle database.</p><small>You can continue manually. This visit will remain marked as unmatched.</small></div></div>)}<StepError error={error} /><div className="operation-actions"><span /><button onClick={nextFromVehicle}>Continue to driver →</button></div></div>}
      {step === 2 && <div className="operation-step"><p className="step-label">STEP 2 OF 4</p><h3>Who is driving?</h3><p className="step-help">Select a known driver or enter a name manually.</p><label>Driver name<input list="known-drivers" value={driverName} onChange={(event) => setDriverName(event.target.value)} placeholder="Search or type driver name" /></label><datalist id="known-drivers">{drivers.filter((item) => item.active !== false).map((item) => <option key={item.id} value={item.fullName}>{item.telephone}</option>)}</datalist>{driverName.trim() && (driver ? <div className="match-card success"><span aria-hidden="true">✓</span><div><strong>{driver.fullName}</strong><p>{driver.telephone || "No telephone recorded"}</p><small>Driver found in database</small></div></div> : <div className="match-card warning"><span aria-hidden="true">!</span><div><strong>Driver not found</strong><p>You can continue with this manually entered name.</p><small>This visit will remain marked as unmatched.</small></div></div>)}<StepError error={error} /><div className="operation-actions"><button className="secondary" onClick={() => setStep(1)}>← Back</button><button onClick={nextFromDriver}>Continue →</button></div></div>}
      {step === 3 && <div className="operation-step"><p className="step-label">STEP 3 OF 4</p><h3>Where did this load come from?</h3><p className="step-help">Use the usual vehicle route as a suggestion, but record the actual route for this trip.</p><label>Collection site / route<input value={route} onChange={(event) => setRoute(event.target.value)} placeholder="Enter actual route for this trip" /></label>{vehicle?.route && <button className="suggestion" onClick={() => setRoute(vehicle.route)}>Use usual route: {vehicle.route}</button>}<label>Arrival time<div className="time-row"><input type="time" value={arrivalTime} onChange={(event) => setArrivalTime(event.target.value)} /><button onClick={() => setArrivalTime(currentTime())}>Use current time</button></div></label><StepError error={error} /><div className="operation-actions"><button className="secondary" onClick={() => setStep(2)}>← Back</button><button onClick={nextFromArrival}>Continue to weight →</button></div></div>}
      {step === 4 && <div className="operation-step weight-step"><p className="step-label">STEP 4 OF 4</p><h3>{resumeEntry ? "Complete open transaction" : "Enter weighbridge readings"}</h3><p className="step-help">Enter gross now. If tare is not yet known, save the transaction as open and complete it when the vehicle returns.</p>{resumeEntry && <p className="resume-banner">Open transaction resumed · {resumeEntry.registration}</p>}<div className="weight-grid"><label>Gross weight<div className={weightWarning && grossKg <= 0 ? "invalid-weight" : ""}><input type="number" min="1" inputMode="numeric" value={gross} onChange={(event) => setGross(event.target.value)} placeholder="0" aria-invalid={Boolean(weightWarning && grossKg <= 0)} /><span>kg</span></div></label><label>Tare weight<div className={weightWarning && tareKg > 0 ? "invalid-weight" : ""}><input type="number" min="1" inputMode="numeric" value={tare} onChange={(event) => setTare(event.target.value)} placeholder="0" aria-invalid={Boolean(weightWarning && tareKg > 0)} /><span>kg</span></div></label></div>{weightWarning && <p className="live-weight-warning" role="status">{weightWarning}</p>}{vehicle?.tareKg && <p className="tare-note">The tare value is a vehicle suggestion and remains editable while the operational tare workflow needs confirmation.</p>}<div className={netKg > 0 ? "net-result ready" : "net-result"}><p>NET WASTE</p><strong>{netKg.toLocaleString()} <small>kg</small></strong><span>{(netKg / 1000).toFixed(2)} tonnes</span></div><label className="departure-field">Departure time<div className="time-row"><input type="time" value={departureTime} onChange={(event) => setDepartureTime(event.target.value)} /><button onClick={() => setDepartureTime(currentTime())}>Use current time</button></div><small>Recorded only when you complete the transaction.</small></label><StepError error={error} /><div className="transaction-review"><span>{registration}</span><span>{driverName}</span><span>{route}</span><span>Arrival {arrivalTime}</span><span>Departure {departureTime}</span></div><div className="operation-actions weight-actions"><button className="secondary" onClick={() => setStep(3)}>← Back</button><div><button className="secondary save-open" onClick={() => saveEntry("OPEN")}>Save as open</button><button onClick={reviewCompletion}>Review and complete →</button></div></div></div>}
      {step === 5 && completed && <div className="complete-step"><span className="complete-mark">✓</span><p className="step-label">{completed.status === "OPEN" ? "TRANSACTION SAVED AS OPEN" : "TRANSACTION COMPLETED"}</p><h3>{completed.registration}</h3><div className="complete-weight"><strong>{completed.status === "OPEN" ? `${completed.grossKg.toLocaleString()} kg gross` : `${completed.netKg.toLocaleString()} kg`}</strong><span>{completed.status === "OPEN" ? "Waiting for tare weight" : `${(completed.netKg / 1000).toFixed(2)} tonnes net waste`}</span></div><dl><div><dt>Driver</dt><dd>{completed.driverName}{!completed.driverMatched && " · Unmatched"}</dd></div><div><dt>Route</dt><dd>{completed.routeSource}</dd></div><div><dt>Arrival</dt><dd>{completed.arrivalTime}</dd></div><div><dt>Departure</dt><dd>{completed.departureTime || "Pending"}</dd></div><div><dt>Status</dt><dd>{completed.status === "OPEN" ? "Open · tare pending" : "Completed ✓"}</dd></div></dl><p className="saved-message">{completed.status === "OPEN" ? "Saved safely on this device. Open this record from Records when the tare weight is available." : "Saved on this device. It will be migrated to Firestore when the production data layer is connected."}</p><button onClick={reset}>＋ Record next vehicle</button></div>}
    </section>
    {confirmingCompletion && <><button className="completion-scrim" aria-label="Cancel completion review" onClick={() => setConfirmingCompletion(false)} /><section className="completion-review-dialog" role="dialog" aria-modal="true" aria-labelledby="completion-review-title"><p className="step-label">FINAL CHECK</p><h3 id="completion-review-title">Complete this transaction?</h3><p>Review the weighbridge readings before they become a completed record.</p><dl><div><dt>Vehicle</dt><dd>{registration}</dd></div><div><dt>Driver</dt><dd>{driverName}</dd></div><div><dt>Route</dt><dd>{route}</dd></div><div><dt>Arrival / departure</dt><dd>{arrivalTime} → {departureTime}</dd></div><div><dt>Gross</dt><dd>{grossKg.toLocaleString()} kg</dd></div><div><dt>Tare</dt><dd>{tareKg.toLocaleString()} kg</dd></div><div className="review-net"><dt>Net waste</dt><dd>{netKg.toLocaleString()} kg · {(netKg / 1000).toFixed(2)} tonnes</dd></div></dl><div className="completion-review-actions"><button onClick={() => setConfirmingCompletion(false)}>Go back and edit</button><button onClick={() => saveEntry("COMPLETED")}>Confirm completion ✓</button></div></section></>}
  </div>;
}

function StepError({ error }: { error: string }) { return error ? <p className="step-error" role="alert">{error}</p> : null; }
