"use client";

import { FormEvent, useState } from "react";
import { logAudit } from "../../utils/localAudit";

type Correction = { correctedAt: string; correctedBy?: string; reason: string; before: Record<string, string>; after: Record<string, string> };
type Entry = { id: string; facilityId?: string; localTicket?: string; createdBy?: string; registration: string; vehicleMatched: boolean; vehicleType?: string; division?: string; originArea?: string; operatorCategory?: string; company?: string; concessionaire?: string; driverName: string; driverMatched: boolean; driverPhone: string; routeSource: string; arrivalTime: string; departureTime?: string; grossKg: number; tareKg: number; netKg: number; tareCaptureMode?: "UNCONFIRMED"; status: "OPEN" | "COMPLETED" | "VOIDED"; operationDate: string; completedAt: string; voidReason?: string; voidedAt?: string; voidedBy?: string; correctionHistory?: Correction[] };
function operatorCategory(entry: Entry) { return entry.operatorCategory || (entry.concessionaire === "Yes" ? "Concessionaire" : entry.concessionaire === "No" ? "Non-concessionaire" : "Unconfirmed"); }
const entriesKey = "buyala.local.entries.v1";

function readEntries(): Entry[] { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem(entriesKey) ?? "[]") as Entry[]; } catch { return []; } }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-UG", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`)); }
function minutesBetween(start?: string, end?: string) { if (!start || !end) return null; const [sh, sm] = start.split(":").map(Number); const [eh, em] = end.split(":").map(Number); const minutes = eh * 60 + em - (sh * 60 + sm); return minutes >= 0 ? minutes : minutes + 1440; }
function dateBounds() { const now = new Date(); const today = now.toISOString().slice(0, 10); const yesterday = new Date(now); yesterday.setDate(now.getDate() - 1); const week = new Date(now); week.setDate(now.getDate() - ((now.getDay() + 6) % 7)); return { today, yesterday: yesterday.toISOString().slice(0, 10), weekStart: week.toISOString().slice(0, 10), monthStart: `${today.slice(0, 7)}-01` }; }

export function RecordsView({ onContinueEntry, canManage = true, actorName = "Local engineer" }: { onContinueEntry?: (id: string) => void; canManage?: boolean; actorName?: string }) {
  const [entries, setEntries] = useState<Entry[]>(readEntries);
  const [search, setSearch] = useState("");
  const [dateFilter, setDateFilter] = useState("all");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [status, setStatus] = useState("all");
  const [division, setDivision] = useState("all");
  const [concessionaire, setConcessionaire] = useState("all");
  const [matchQuality, setMatchQuality] = useState("all");
  const [selected, setSelected] = useState<Entry | null>(null);
  const bounds = dateBounds();
  const divisions = [...new Set(entries.map((entry) => entry.division).filter(Boolean) as string[])].sort();
  const filtered = (() => {
    const query = search.trim().toLowerCase();
    return [...entries].filter((entry) => {
      const matchesSearch = !query || [entry.registration, entry.driverName, entry.routeSource, entry.company ?? ""].some((value) => value.toLowerCase().includes(query));
      const matchesDate = dateFilter === "all" || (dateFilter === "today" && entry.operationDate === bounds.today) || (dateFilter === "yesterday" && entry.operationDate === bounds.yesterday) || (dateFilter === "week" && entry.operationDate >= bounds.weekStart && entry.operationDate <= bounds.today) || (dateFilter === "month" && entry.operationDate >= bounds.monthStart && entry.operationDate <= bounds.today) || (dateFilter === "custom" && (!dateFrom || entry.operationDate >= dateFrom) && (!dateTo || entry.operationDate <= dateTo));
      const matchesQuality = matchQuality === "all" || (matchQuality === "matched" && entry.vehicleMatched && entry.driverMatched) || (matchQuality === "attention" && (!entry.vehicleMatched || !entry.driverMatched)) || (matchQuality === "vehicle" && !entry.vehicleMatched) || (matchQuality === "driver" && !entry.driverMatched);
      return matchesSearch && matchesDate && matchesQuality && (status === "all" || entry.status === status) && (division === "all" || (entry.division || "Unconfirmed") === division) && (concessionaire === "all" || operatorCategory(entry) === concessionaire);
    }).sort((a, b) => b.completedAt.localeCompare(a.completedAt));
  })();
  const totalNet = filtered.filter((entry) => entry.status === "COMPLETED").reduce((sum, entry) => sum + entry.netKg, 0);
  const exceptions = filtered.filter((entry) => !entry.vehicleMatched || !entry.driverMatched).length;
  const activeFilters = [search.trim(), dateFilter !== "all" ? dateFilter : "", status !== "all" ? status : "", division !== "all" ? division : "", concessionaire !== "all" ? concessionaire : "", matchQuality !== "all" ? matchQuality : ""].filter(Boolean).length;
  function clearFilters() { setSearch(""); setDateFilter("all"); setDateFrom(""); setDateTo(""); setStatus("all"); setDivision("all"); setConcessionaire("all"); setMatchQuality("all"); }
  function voidEntry(id: string, reason: string) { const updated = entries.map((entry) => entry.id === id ? { ...entry, status: "VOIDED" as const, voidReason: reason, voidedAt: new Date().toISOString(), voidedBy: actorName } : entry); setEntries(updated); localStorage.setItem(entriesKey, JSON.stringify(updated)); const changed = updated.find((entry) => entry.id === id); if (changed) logAudit(actorName, "Engineer", "TRANSACTION_VOIDED", `Voided ${changed.registration}: ${reason}`, changed.localTicket); setSelected(changed ?? null); }
  function correctEntry(id: string, values: { originArea: string; division: string; operatorCategory: string; company: string; routeSource: string; departureTime: string; reason: string }) {
    const current = entries.find((entry) => entry.id === id); if (!current) return;
    const before = { originArea: current.originArea ?? "", division: current.division ?? "", operatorCategory: operatorCategory(current), company: current.company ?? "", routeSource: current.routeSource, departureTime: current.departureTime ?? "" };
    const after = { originArea: values.originArea, division: values.division, operatorCategory: values.operatorCategory, company: values.company, routeSource: values.routeSource, departureTime: values.departureTime };
    const correction: Correction = { correctedAt: new Date().toISOString(), correctedBy: actorName, reason: values.reason, before, after };
    const updated = entries.map((entry) => entry.id === id ? { ...entry, ...after, concessionaire: values.operatorCategory === "Concessionaire" ? "Yes" : values.operatorCategory === "Non-concessionaire" ? "No" : "", correctionHistory: [...(entry.correctionHistory ?? []), correction] } : entry);
    setEntries(updated); localStorage.setItem(entriesKey, JSON.stringify(updated)); logAudit(actorName, "Engineer", "RECORD_CORRECTED", `Corrected reporting details for ${current.registration}: ${values.reason}`, current.localTicket); setSelected(updated.find((entry) => entry.id === id) ?? null);
  }

  return <div className="records-page">
    <div className="records-heading"><div><p className="master-kicker">TRANSACTION HISTORY</p><h2>Records</h2><p>Search and review locally saved weighbridge entries.</p></div><span className="record-store-state">● Saved on this device</span></div>
    <div className="records-summary"><article><strong>{filtered.length}</strong><span>Transactions shown</span></article><article><strong>{(totalNet / 1000).toFixed(2)} t</strong><span>Completed net waste</span></article><article className={exceptions ? "attention" : ""}><strong>{exceptions}</strong><span>Unmatched records</span></article></div>
    <section className="records-card">
      <div className="records-filters">
        <label className="record-search"><span className="sr-only">Search records</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search vehicle, driver, company or route" /></label>
        <select aria-label="Date filter" value={dateFilter} onChange={(event) => setDateFilter(event.target.value)}><option value="all">All dates</option><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="week">This week</option><option value="month">This month</option><option value="custom">Custom date range</option></select>
        {dateFilter === "custom" && <div className="record-date-range"><label>From<input aria-label="Records from date" type="date" value={dateFrom} max={dateTo || undefined} onChange={(event) => setDateFrom(event.target.value)} /></label><label>To<input aria-label="Records to date" type="date" value={dateTo} min={dateFrom || undefined} onChange={(event) => setDateTo(event.target.value)} /></label></div>}
        <select aria-label="Status filter" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="COMPLETED">Completed</option><option value="OPEN">Open</option><option value="VOIDED">Voided</option></select>
        <select aria-label="Division filter" value={division} onChange={(event) => setDivision(event.target.value)}><option value="all">All divisions</option>{divisions.map((item) => <option key={item}>{item}</option>)}<option value="Unconfirmed">Unconfirmed</option></select>
        <select aria-label="Operator category filter" value={concessionaire} onChange={(event) => setConcessionaire(event.target.value)}><option value="all">All operator categories</option><option value="KCCA direct">KCCA direct</option><option value="Concessionaire">Concessionaire</option><option value="Non-concessionaire">Non-concessionaire</option><option value="Unconfirmed">Unconfirmed</option></select>
        <select aria-label="Database match filter" value={matchQuality} onChange={(event) => setMatchQuality(event.target.value)}><option value="all">All database matches</option><option value="matched">Fully matched</option><option value="attention">Needs attention</option><option value="vehicle">Unknown vehicle</option><option value="driver">Unknown driver</option></select>
      </div>
      <div className="filter-results-bar"><span>Showing <b>{filtered.length}</b> of {entries.length} transactions{activeFilters ? ` · ${activeFilters} filter${activeFilters === 1 ? "" : "s"} active` : ""}</span>{activeFilters > 0 && <button onClick={clearFilters}>Clear all filters</button>}</div>
      {filtered.length === 0 ? <div className="records-empty"><span aria-hidden="true">R</span><h3>{entries.length ? "No records match these filters" : "No transactions recorded yet"}</h3><p>{entries.length ? "Change or clear a filter to see more records." : "Complete a vehicle transaction in Daily Operations and it will appear here."}</p></div> : <><div className="records-table"><div className="records-row records-header"><span>Date / time</span><span>Vehicle</span><span>Driver</span><span>Route</span><span>Net weight</span><span>Status</span></div>{filtered.map((entry) => <button className="records-row" key={entry.id} onClick={() => setSelected(entry)}><span><strong>{formatDate(entry.operationDate)}</strong><small>{entry.arrivalTime}</small></span><span><strong>{entry.registration}</strong><small>{entry.division || "Division unconfirmed"}</small></span><span><strong>{entry.driverName}</strong><small>{entry.driverMatched ? entry.driverPhone || "Matched" : "Unmatched driver"}</small></span><span>{entry.routeSource}</span><span><strong>{entry.status === "OPEN" ? "Tare pending" : `${entry.netKg.toLocaleString()} kg`}</strong><small>{entry.status === "COMPLETED" ? `${(entry.netKg / 1000).toFixed(2)} t` : ""}</small></span><Status entry={entry} /></button>)}</div><div className="records-mobile-list">{filtered.map((entry) => <button className="record-mobile-card" key={entry.id} onClick={() => setSelected(entry)}><div><strong>{entry.registration}</strong><span>{entry.driverName}</span></div><div><strong>{entry.status === "OPEN" ? "Tare pending" : `${entry.netKg.toLocaleString()} kg`}</strong><span>{formatDate(entry.operationDate)} · {entry.arrivalTime}</span></div><p>{entry.routeSource} · {entry.division || "Unconfirmed division"}</p><Status entry={entry} />{(!entry.vehicleMatched || !entry.driverMatched) && <b>Needs attention</b>}</button>)}</div></>}
    </section>
    {selected && <RecordDetail entry={selected} canManage={canManage} onClose={() => setSelected(null)} onContinue={() => onContinueEntry?.(selected.id)} onVoid={(reason) => voidEntry(selected.id, reason)} onCorrect={(values) => correctEntry(selected.id, values)} />}
  </div>;
}

function Status({ entry }: { entry: Entry }) { return <span className={`record-status ${entry.status.toLowerCase()}`}>{entry.status === "COMPLETED" ? "Completed ✓" : entry.status}</span>; }
function DetailSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="detail-section"><h4>{title}</h4><dl>{children}</dl></section>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }

function RecordDetail({ entry, onClose, onContinue, onVoid, onCorrect, canManage }: { entry: Entry; onClose: () => void; onContinue: () => void; onVoid: (reason: string) => void; onCorrect: (values: { originArea: string; division: string; operatorCategory: string; company: string; routeSource: string; departureTime: string; reason: string }) => void; canManage: boolean }) {
  const [showVoid, setShowVoid] = useState(false); const [showCorrection, setShowCorrection] = useState(false); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const turnaround = minutesBetween(entry.arrivalTime, entry.departureTime);
  function confirmVoid() { if (!reason.trim()) return setError("Enter a reason before voiding this transaction."); onVoid(reason.trim()); setShowVoid(false); }
  function submitCorrection(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const correctionReason = String(data.get("correctionReason") ?? "").trim(); if (!correctionReason) return setError("Enter a reason for this correction."); onCorrect({ originArea: String(data.get("originArea") ?? ""), division: String(data.get("division") ?? "").trim(), operatorCategory: String(data.get("operatorCategory") ?? ""), company: String(data.get("company") ?? "").trim(), routeSource: String(data.get("routeSource") ?? "").trim(), departureTime: String(data.get("departureTime") ?? ""), reason: correctionReason }); setShowCorrection(false); setError(""); }
  return <><button className="detail-scrim" aria-label="Close record details" onClick={onClose} /><aside className={canManage ? "record-detail" : "record-detail readonly"} role="dialog" aria-modal="true" aria-labelledby="record-detail-title">
    <div className="detail-heading"><div><p className="master-kicker">TRANSACTION DETAIL</p><h3 id="record-detail-title">{entry.registration}</h3><Status entry={entry} /></div><button aria-label="Close details" onClick={onClose}>×</button></div>
    {entry.status === "OPEN" && <section className="continue-open"><strong>Tare weight pending</strong><p>Continue this transaction when the vehicle returns to the scale.</p><button onClick={onContinue}>Continue transaction →</button></section>}
    <DetailSection title="Identification"><Detail label="Date" value={formatDate(entry.operationDate)} /><Detail label="Facility" value={entry.facilityId === "buyala" ? "Buyala" : "Buyala · local record"} /><Detail label="Local ticket" value={entry.localTicket || `Legacy · ${entry.id.slice(0, 8).toUpperCase()}`} /><Detail label="Recorded by" value={entry.createdBy || "Older local record"} /></DetailSection>
    <DetailSection title="Vehicle snapshot"><Detail label="Registration" value={entry.registration} /><Detail label="Vehicle type" value={entry.vehicleType || "Not recorded"} /><Detail label="Origin area" value={entry.originArea || "Unconfirmed"} /><Detail label="Kampala division" value={entry.division || "Unconfirmed / not applicable"} /><Detail label="Operator category" value={operatorCategory(entry)} /><Detail label="Company / owner" value={entry.company || "Not recorded"} /><Detail label="Database match" value={entry.vehicleMatched ? "Matched ✓" : "Unmatched"} /></DetailSection>
    <DetailSection title="Driver"><Detail label="Name" value={entry.driverName} /><Detail label="Telephone" value={entry.driverPhone || "Not recorded"} /><Detail label="Database match" value={entry.driverMatched ? "Matched ✓" : "Unmatched"} /></DetailSection>
    <DetailSection title="Source and timing"><Detail label="Route / source" value={entry.routeSource} /><Detail label="Arrival" value={entry.arrivalTime} /><Detail label="Departure" value={entry.departureTime || (entry.status === "OPEN" ? "Pending — complete later" : "Not recorded — older entry")} /><Detail label="Turnaround" value={turnaround === null ? (entry.status === "OPEN" ? "Pending" : "Unavailable without departure") : `${turnaround} minutes`} /></DetailSection>
    <section className="detail-weight"><p>WEIGHT</p><div><span>Gross<strong>{entry.grossKg.toLocaleString()} kg</strong></span><span>Tare<strong>{entry.status === "OPEN" ? "Pending" : `${entry.tareKg.toLocaleString()} kg`}</strong></span><span className="net">Net<strong>{entry.status === "OPEN" ? "Pending" : `${entry.netKg.toLocaleString()} kg`}</strong>{entry.status !== "OPEN" && <small>{(entry.netKg / 1000).toFixed(2)} tonnes</small>}</span></div></section>
    {entry.status !== "VOIDED" && <section className="correction-panel"><div><strong>Reporting details</strong><p>Correct classification, route, or missing departure details without changing recorded weights.</p></div>{showCorrection ? <form onSubmit={submitCorrection}><div className="correction-grid"><label>Origin area<select name="originArea" defaultValue={entry.originArea ?? ""}><option value="">Unconfirmed</option><option value="Kampala city">Kampala city</option><option value="Nearby suburbs / outside Kampala">Nearby suburbs / outside Kampala</option></select></label><label>Kampala division<input name="division" defaultValue={entry.division ?? ""} list="correction-divisions" /><datalist id="correction-divisions"><option value="Central" /><option value="Nakawa" /><option value="Makindye" /><option value="Kawempe" /><option value="Rubaga / Lubaga" /></datalist></label><label>Operator category<select name="operatorCategory" defaultValue={operatorCategory(entry)}><option value="Unconfirmed">Unconfirmed</option><option value="KCCA direct">KCCA direct</option><option value="Concessionaire">Concessionaire</option><option value="Non-concessionaire">Non-concessionaire</option></select></label><label>Company / owner<input name="company" defaultValue={entry.company ?? ""} /></label><label>Route / source<input name="routeSource" defaultValue={entry.routeSource} required /></label><label>Departure time<input name="departureTime" type="time" defaultValue={entry.departureTime ?? ""} /></label></div><label>Reason for correction *<textarea name="correctionReason" rows={2} placeholder="Explain why these details are being changed" /></label>{error && <span className="correction-error" role="alert">{error}</span>}<div className="correction-actions"><button type="button" onClick={() => { setShowCorrection(false); setError(""); }}>Cancel</button><button type="submit">Save audited correction</button></div></form> : <button onClick={() => { setShowCorrection(true); setShowVoid(false); setError(""); }}>Correct reporting details</button>}</section>}
    {entry.correctionHistory && entry.correctionHistory.length > 0 && <section className="correction-history"><h4>CORRECTION HISTORY</h4>{[...entry.correctionHistory].reverse().map((correction, index) => <article key={`${correction.correctedAt}-${index}`}><strong>{new Date(correction.correctedAt).toLocaleString("en-UG")}</strong><p>{correction.reason}</p><small>Original and corrected values retained in the local audit record.</small></article>)}</section>}
    {entry.status === "VOIDED" ? <section className="voided-record"><strong>Transaction voided</strong><p>{entry.voidReason}</p><small>Original values have been retained for audit.</small></section> : <section className="record-safety"><p>{entry.status === "OPEN" ? "Open records remain incomplete until tare is entered. If this visit is invalid, void it and record the reason." : "Completed records cannot be deleted. If this transaction is invalid, void it and record the reason."}</p>{showVoid ? <div className="void-form"><label>Reason for voiding<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} placeholder="Explain why this record is invalid" /></label>{error && <span role="alert">{error}</span>}<div><button onClick={() => setShowVoid(false)}>Cancel</button><button onClick={confirmVoid}>Confirm void</button></div></div> : <button onClick={() => setShowVoid(true)}>Void transaction</button>}</section>}
    {!canManage && entry.status !== "VOIDED" && <section className="role-readonly"><strong>Engineer approval required</strong><p>Data Clerks can review records and complete open transactions. Corrections and voids are restricted to the Engineer account.</p></section>}
    <p className="detail-note">Tare capture mode remains NEEDS CONFIRMATION. Firebase will add authoritative user and timestamp audit fields.</p>
  </aside></>;
}
