"use client";

import { FormEvent, useState } from "react";
import { logAudit } from "../../utils/localAudit";
import { readAudit } from "../../utils/localAudit";
import { LocalAccount, readLocalAccounts, saveLocalAccounts } from "../../utils/localAccounts";

function initials(name: string) { return name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "DC"; }
function accountActivity(username: string) { const events = readAudit().filter((event) => event.reference === username || (event.action === "SIGN_IN" && event.actor.toLowerCase().includes(username.toLowerCase()))); const signIns = events.filter((event) => event.action === "SIGN_IN"); return { lastSignIn: signIns.at(-1)?.at, signInCount: signIns.length }; }

export function AccountManagementView({ engineerName }: { engineerName: string }) {
  const [accounts, setAccounts] = useState<LocalAccount[]>(readLocalAccounts);
  const [resetting, setResetting] = useState<string | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  function persist(next: LocalAccount[]) { setAccounts(next); saveLocalAccounts(next); }
  function toggleAccount(username: string) { const target = accounts.find((account) => account.username === username); if (!target || target.role === "Engineer") return; const next = accounts.map((account) => account.username === username ? { ...account, active: !account.active } : account); persist(next); setMessage(`${target.name} ${target.active ? "deactivated" : "reactivated"}.`); logAudit(engineerName, "Engineer", target.active ? "ACCOUNT_DEACTIVATED" : "ACCOUNT_REACTIVATED", `${target.active ? "Deactivated" : "Reactivated"} Data Clerk ${target.name}`, username); }
  function createClerk(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); const form = event.currentTarget; const data = new FormData(form); const name = String(data.get("fullName") ?? "").trim(); const username = String(data.get("username") ?? "").trim().toLowerCase().replace(/\s+/g, ""); const password = String(data.get("password") ?? ""); const confirmation = String(data.get("confirmPassword") ?? ""); if (!name) return setError("Enter the clerk's full name."); if (!/^[a-z0-9._-]{3,30}$/.test(username)) return setError("Use 3–30 lowercase letters, numbers, dots, underscores or hyphens for the username."); if (accounts.some((account) => account.username === username)) return setError("That username already exists."); if (password.length < 10) return setError("Use a temporary password with at least 10 characters."); if (password !== confirmation) return setError("The two passwords do not match."); const account: LocalAccount = { username, password, name, role: "Data Clerk", initials: initials(name), active: true, createdAt: new Date().toISOString(), mustChangePassword: true }; persist([...accounts, account]); logAudit(engineerName, "Engineer", "ACCOUNT_CREATED", `Created Data Clerk account for ${name}`, username); setMessage(`Data Clerk account created for ${name}. They must change the temporary password at first sign-in.`); setShowCreate(false); form.reset(); }
  function resetPassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); if (!resetting) return; const form = event.currentTarget; const data = new FormData(form); const password = String(data.get("newPassword") ?? ""); const confirmation = String(data.get("confirmPassword") ?? ""); if (password.length < 10) return setError("Use at least 10 characters."); if (password !== confirmation) return setError("The two passwords do not match."); const next = accounts.map((account) => account.username === resetting ? { ...account, password, mustChangePassword: true } : account); persist(next); const changed = next.find((account) => account.username === resetting); setMessage(`${changed?.name ?? "Account"} received a temporary password and must replace it at the next sign-in.`); logAudit(engineerName, "Engineer", "PASSWORD_RESET", `Issued a temporary local password for ${changed?.name ?? resetting}`, resetting); setResetting(null); form.reset(); }

  return <div className="accounts-page">
    <div className="accounts-heading"><div><p className="master-kicker">LOCAL ACCESS CONTROL</p><h2>User accounts</h2><p>Create and manage accounts used during this computer-based pilot.</p></div><div className="accounts-heading-actions"><span>Engineer only</span><button onClick={() => { setShowCreate(true); setResetting(null); setError(""); setMessage(""); }}>＋ Create Data Clerk</button></div></div>
    {message && <p className="account-message" role="status">{message}</p>}
    {showCreate && <section className="create-account-panel"><div><p className="master-kicker">NEW LOCAL ACCOUNT</p><h3>Create Data Clerk</h3><p>The new clerk receives operational permissions only.</p></div><form onSubmit={createClerk}><label>Full name<input name="fullName" required /></label><label>Username<input name="username" required autoCapitalize="none" autoComplete="off" placeholder="e.g. clerk.jane" /></label><label>Temporary password<input name="password" type="password" minLength={10} required autoComplete="new-password" /></label><label>Confirm password<input name="confirmPassword" type="password" minLength={10} required autoComplete="new-password" /></label>{error && <span role="alert">{error}</span>}<div><button type="button" onClick={() => { setShowCreate(false); setError(""); }}>Cancel</button><button type="submit">Create account</button></div></form></section>}
    <div className="account-cards">{accounts.map((account) => { const activity = accountActivity(account.username); return <article key={account.username} className={account.active ? "" : "disabled"}><div className="account-avatar">{account.initials}</div><div><p>{account.role}</p><h3>{account.name}</h3><span>Username: <b>{account.username}</b></span><small>{account.mustChangePassword ? "Temporary password change required" : account.passwordChangedAt ? `Password changed ${new Date(account.passwordChangedAt).toLocaleDateString("en-UG")}` : "Using initial pilot password"}</small><small>{activity.lastSignIn ? `Last sign-in ${new Date(activity.lastSignIn).toLocaleString("en-UG")} · ${activity.signInCount} total` : "No recorded sign-in yet"}</small></div><div className="account-state"><b>{account.active ? "Active" : "Inactive"}</b><button onClick={() => { setResetting(account.username); setShowCreate(false); setError(""); setMessage(""); }}>Reset password</button>{account.role === "Data Clerk" ? <button className="toggle-account" onClick={() => toggleAccount(account.username)}>{account.active ? "Deactivate" : "Reactivate"}</button> : <small>Protected account</small>}</div></article>; })}</div>
    {resetting && <section className="password-reset-panel"><div><p className="master-kicker">RESET LOCAL PASSWORD</p><h3>{accounts.find((account) => account.username === resetting)?.name}</h3><p>This becomes a temporary password that must be replaced at the next sign-in.</p></div><form onSubmit={resetPassword}><label>New password<input name="newPassword" type="password" minLength={10} required autoComplete="new-password" /></label><label>Confirm password<input name="confirmPassword" type="password" minLength={10} required autoComplete="new-password" /></label>{error && <span role="alert">{error}</span>}<div><button type="button" onClick={() => { setResetting(null); setError(""); }}>Cancel</button><button type="submit">Update password</button></div></form></section>}
    <section className="permissions-panel"><div><p className="master-kicker">ROLE PERMISSIONS</p><h3>Who can do what</h3><p>Permissions are fixed for this pilot to reduce mistakes and protect completed records.</p></div><div className="permissions-table" role="table" aria-label="Role permissions"><div className="permissions-row heading" role="row"><span>Action</span><b>Data Clerk</b><b>Engineer</b></div>{[["Record and complete vehicles",true,true],["Manage vehicles and drivers",true,true],["View operational records",true,true],["Correct or void completed records",false,true],["View and export reports",false,true],["Manage accounts and audit log",false,true]].map(([label,clerk,engineer]) => <div className="permissions-row" role="row" key={String(label)}><span>{label}</span><b className={clerk ? "allowed" : "denied"}>{clerk ? "✓ Yes" : "— No"}</b><b className={engineer ? "allowed" : "denied"}>{engineer ? "✓ Yes" : "— No"}</b></div>)}</div></section>
    <section className="local-security-note"><strong>Local pilot limitation</strong><p>Passwords are stored only in this browser for local testing. Firebase Authentication will securely manage credentials, password recovery and account administration before hosting.</p></section>
  </div>;
}
